VER=0.1.1

# Must be LOWERCASE
USER=8ch9azbsfifz
REPO=rockprog
TAG=ghcr.io/${USER}/${REPO}/rockprog

build:
	docker build . -t ${TAG}:${VER} -t ${TAG}:latest

run:
	docker run --rm -it --privileged -v /dev/bus/usb:/dev/bus/usb ${TAG}:${VER} -l


push:
	docker push ${TAG}:${VER}

